package mypackage;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Created by TinTin on 6/27/16.
 * Professor class that will import
 * google spreadsheet ID and passcode
 * that generated from them
 */
public class Professor {

    private static List<List<String>> professorIdentity = new ArrayList<>();

    /**
     * Import spreadsheet ID and
     * passcode enter by professor
     * to List class
     * @param spreadsheetID
     * @param passcode
     */
    public static void importSpreadsheetIDandPasscode(String spreadsheetID, String passcode) {
        List<String> arrayList = new ArrayList<>();
        arrayList.add(spreadsheetID);
        arrayList.add(passcode);
        professorIdentity.add(arrayList);
    }


    /**
     * Find the passcodes input by students
     * and compare them with all the passcodes
     * generated by professors. Check to see
     * if there is a match. Otherwise return false
     * because student has input the wrong passcode
     * that does not match any of the passcode
     * generated by the professor
     */

    public static boolean passcodeExist(String passcode) {

        for (List<String> aProfessorIdentity : professorIdentity)
            if (aProfessorIdentity.get(1).equals(passcode)) {
                return true;
            }
        return false;
    }

    public static void getProfessorIdentity() {
        System.out.println(professorIdentity);
    }

    public static void main(String argv[]) {

    }
}
