/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Harmony' at '6/6/16 2:39 PM' with Gradle 2.13
 *
 * @author Harmony, @date 6/6/16 2:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
