/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Harmony' at '6/27/16 10:50 AM' with Gradle 2.13
 *
 * @author Harmony, @date 6/27/16 10:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
